### ISSUE TITLE
Haven seemed to be in standby 

### ISSUE THREAD

**Issue by leonardoporpora** [guardianproject/haven#136] opened 2017-12-27 18:50 UTC
After 8 hours that it worked perfectly my mum went sleeping and than about 10 hours later she entered in my room made some stuff but I haven’t received anything. A day after I came in my room and I started receiving alerts just when I unlocked the phone. And there were no logs.

**Comment by n8fr8** [comment] 2017-12-27 19:00
Can you tell us more about your phone type and OS version?

**Comment by leonardoporpora** [comment] 2017-12-27 19:07
It’s a Samsung Galaxy J3 (2016) Version of Android 5.1.1 Kernel version 3.10.65-12057946

**Comment by licaon-kter** [comment] 2017-12-27 19:23
Did you disable battery optimisation for the app?

**Comment by leonardoporpora** [comment] 2017-12-27 19:24
@licaon-kter yes I did

**Comment by leonardoporpora** [comment] 2017-12-28 12:20
Have you got any idea of how can I fix it. I studied it and it works perfectly the first time that it notices new movements but after that if there is no movements for like 15 minutes and than I come back into my room I do not receive any alarm.

**Comment by leonardoporpora** [comment] 2017-12-30 11:32
@n8fr8 @licaon-kter have you got any idea of how can we fix it is a really big problem cause if there is a false positive detected by Haven and then it goes in standby when thieves come in my room Haven won’t detect anything.

**Comment by n8fr8** [comment] 2018-01-17 15:15
Let's call this ticket a duplicate of #111 - some progress happening that I've tagged with that issue. Please test the latest beta when it is out.

**Closed by n8fr8** 2018-01-17 15:15 UTC
