### ISSUE TITLE
Logs cannot be deleted in Android 7

### ISSUE THREAD

**Issue by axbl** [guardianproject/haven#354] opened 2018-10-21 09:45 UTC
The deleting of Logs is still not fixed.
Using the Menu "Delete all Logs" wipes the Logs.
Also I can wipe a log swiping it to a side.
But when I restart or choose Menu and then Back all Logs are still there.

**Comment by deviantollam** [comment] 2018-11-07 20:18
i found (and reported in a different issue, #333) that if Haven attempts to delete a log (by either swipe or menu command) but doesn't find all of the files it was expecting to find within the folder (say, maybe a user moved the photos and such somewhere off of the device) then Haven's delete command kind of shits the bed or something and just gives up.

So the logs appear to vanish, but if you leave that screen and come back... the logs appear back again.  Are you possibly trying to delete logs but have previously removed some image files, etc?

(You can clean all this up, a bit clumsily, by clearing all android app data from Haven.  All logs will finally be gone, but so will any of your configuration settings)

**Comment by archie94** [comment] 2018-11-09 04:16
As reported in #333 Haven's delete command is incomplete if either the database or the file corresponding to any Event Trigger is not removed. Hence even if the files are removed from the storage directory on disk the app keeps a record of the log(s) and leads to an inconsistent state. 

#307 aims to handle this and the bugs due to the 3s delay for 'Undo' better. It is almost done and hopefully, by this weekend I will be able to wrap up the remaining tasks and ready the patch for review.

Big thanks to all for reporting these bugs. Please report more if you find.

**Comment by absorber** [comment] 2018-12-28 18:31
I can confirm this on Android 6 as well.

**Comment by n8fr8** [comment] 2019-02-06 22:15
This all be fixed with the latest merge of #307. Please test nightly from F-Droid and/or wait for the next 0.2.0 release build.

**Comment by n8fr8** [comment] 2019-02-11 15:50
Fixed in the latest 0.2.0 beta 3 release

**Closed by n8fr8** 2019-02-11 15:50 UTC
Labels: for review
